### ISSUE TITLE
Why only exe?

### ISSUE THREAD

**Issue by CaSe2474** [Tiniifan/YKWrandomizer#4]
I don't really know how to mod console games using .exe files, but I DO know how to mod using patch files and roms. Can you give either of those?

**Comment by Tiniifan** [comment]
Hello, please don't open irrelevant issues. Why an .exe? Because the randomizer is a windows application to generate randoms, if you don't have a windows computer you can't generate random, if you have a windows computer follow the official guide [here](https://github.com/Tiniifan/YKWrandomizer/wiki)
