### ISSUE TITLE
Bug at Massiface and Venoct Fight

### ISSUE THREAD

**Issue by Ghost9323** [Tiniifan/YKWrandomizer#5]
before the massiface fight, it will immediately start the fight with no cutscene (forgot if the kyubi cutscene played) and after, you will have no cutscene and fall through the void, eventually landing at the start of the site, after saving the game will play the ending boss fight cutscene and continue as normal
after the venoct fight, it will not play the cutscene and will immediately give you venoct, your objective on both screens will disappear, the Onis will disappear, and McKracken will be unfightable, trying to leave through the elevator results in a black unescapable void.

**Comment by Tiniifan** [comment]
Hi, you should join the discord server to report this kind of problem because the github is only for problems aboutthe tool, not ingame.

Thank you for reporting the problems but I can't really help you, depending on the settings you choose and whether you're playing on 3DS or Citra, if you have game updates installed, you may meet some bugs. 

All randoms are tested on citra with versions 1.0 of the games without any update, so it's recommended to play on citra without any game updates. 

You can try to disable your random and talk to McKraken maybe the battle will start, if the battle doesn't start it's because your save is buggy and there's no solution.

**Comment by Ghost9323** [comment]
@Tiniifan do you know where I can find the discord?

**Comment by Tiniifan** [comment]
Here https://discord.gg/3wKp5ZxA9N
